// Only use the plain text version below
export const PRIVACY_POLICY = [
  'Privacy Policy – CaptureFit',
  '',
  'Effective Date: September 15, 2025',
  'Last Updated: September 15, 2025',
  'App Name: CaptureFit',
  '',
  '1. Information We Collect',
  '- Account Information: Email address, username, password (encrypted), and profile preferences',
  '- Body Progress Photos: Images you choose to upload for progress tracking (avoid photos with face or identifying features)',
  '- Health & Fitness Data: Body measurements, weight, fitness goals, and progress notes',
  '- Communication Data: Messages you send to our support team',
  '- Device Information: Device model, OS version, unique device identifiers, mobile network info',
  '- Usage Analytics: App features used, session duration, crash reports, performance metrics',
  '- Location Data: General location (city/country level) for analytics only',
  '- Camera & Storage Access: Only when you choose to take or upload photos',
  '',
  '2. How We Use Your Information',
  '- Core App Functionality: Progress tracking, photo comparisons, AI-powered analysis',
  '- Personalization: Customizing your experience',
  '- Communication: App updates, security notices, support',
  '- App Improvement: Usage analysis, bug fixes',
  '- Security & Safety: Fraud detection, abuse prevention',
  '- Legal Compliance: Regulatory requirements',
  '',
  'We never use your photos for marketing or advertising.',
  '',
  '3. Data Storage, Security & Retention',
  '- Photos encrypted in transit and at rest (AES-256 via Supabase)',
  '- Data stored on Supabase/AWS servers in the US',
  '- Role-based access controls (RLS) via Supabase',
  '- Supabase maintains SOC 2 Type II compliance',
  '- Photos: Stored until deleted or account closed',
  '- Account Data: Retained while active and 30 days after deletion',
  '- Analytics Data: Anonymized, retained up to 2 years',
  '- Legal Holds: Data may be retained longer if required',
  '',
  '4. Data Sharing & Third Parties',
  '- We DO NOT sell, rent, or trade your info/photos',
  '- No sharing of photos without consent',
  '- No use of images for training AI for other companies',
  '- Minimal data shared with trusted providers (Supabase, AWS)',
  '- Legal disclosure only if required',
  '',
  '5. Your Privacy Rights & Controls',
  '- Delete photos or account anytime',
  '- Request data download',
  '- Privacy rights: access, correction, deletion, portability, objection, restriction',
  '- Email: capturefit1@gmail.com ("Privacy Request")',
  '',
  '6. International Users & Data Transfers',
  '- Data stored/processed on AWS in the US',
  '- Supabase/AWS maintain security certifications',
  '',
  '7. Children\'s Privacy',
  '- Not for users under 18',
  '- No collection from children under 18',
  '- Contact us if you believe a child has provided info',
  '',
  '8. AI & Machine Learning',
  '- On-device and cloud AI analysis',
  '- No use of photos for general-purpose AI training',
  '',
  '9. Cookies & Tracking',
  '- Essential cookies only',
  '- Analytics (anonymized, opt-out available)',
  '- No advertising cookies',
  '',
  '10. Data Breach Notification',
  '- Notify users within 72 hours',
  '- Details and guidance provided',
  '',
  '11. Changes to Policy',
  '- Notification via email and in-app',
  '- Updated effective date',
  '',
  '12. Contact',
  '- Privacy/Support: capturefit1@gmail.com',
  '- Response within 30 days',
  '',
  '',
  'AI Fitness Advice Disclaimer:',
  'CaptureFit includes an AI chatbot that provides general fitness information and suggestions. This advice is for informational purposes only and does not constitute professional medical, fitness, or nutritional advice. Always consult with qualified healthcare professionals before starting any fitness program or making health-related decisions.',
  '',
  'This policy is governed by US law.'
].join('\n');

export const TERMS_OF_SERVICE = [
  'Terms of Service – CaptureFit',
  '',
  'Effective Date: September 15, 2025',
  'Last Updated: September 15, 2025',
  'App Name: CaptureFit',
  '',
  '1. Acceptance of Terms',
  '- By using CaptureFit, you agree to these Terms. If not, do not use the app.',
  '',
  '2. Eligibility',
  '- Must be 18 or older',
  '- Responsible for account credentials and activity',
  '',
  '3. Permitted Use',
  '- Personal, non-commercial use only',
  '- Track fitness, upload photos, analyze data',
  '',
  '4. Prohibited Activities',
  '- No nudity, sexual, or inappropriate photos',
  '- No sharing photos of others without consent',
  '- No harassment, abuse, threats, discrimination',
  '- No hacking, bots, scripts, or disruption',
  '- No illegal use or rights violations',
  '- No commercial use without permission',
  '',
  '5. User Content',
  '- You own your uploaded content',
  '- Grant us license to store/process for app functionality',
  '- Content must be original, legal, and appropriate',
  '- We may remove violating content',
  '',
  '6. Health & Fitness Disclaimers',
  '- Not medical advice',
  '- No health claims',
  '- Use at your own risk',
  '- Consult professionals for health decisions',
  '',
  '7. Privacy & Data Protection',
  '- Governed by our Privacy Policy',
  '',
  '8. Intellectual Property',
  '- App and content owned by CaptureFit',
  '- Limited license to use; no ownership rights',
  '- Trademarks may not be used without permission',
  '',
  '9. Third-Party Services',
  '- Subject to their terms/policies',
  '- No endorsement or responsibility for third-party content',
  '',
  '10. Service Availability',
  '- No guarantee of uninterrupted service',
  '- App may be modified, suspended, or discontinued',
  '- Updates may be required',
  '',
  '11. Account Termination',
  '- You may delete your account anytime',
  '- We may suspend/terminate for violations',
  '- License ends, account/content may be deleted',
  '',
  '12. Disclaimers & Limitation of Liability',
  '- App provided "as is"',
  '- No warranties',
  '- Not liable for indirect, incidental, or consequential damages',
  '- Total liability limited to $100 or amount paid in last 12 months',
  '',
  '13. Indemnification',
  '- You agree to indemnify CaptureFit for claims arising from your use, violations, or content',
  '',
  '14. Dispute Resolution',
  '- Governed by US law',
  '- Informal resolution first',
  '- Binding arbitration if unresolved',
  '- No class actions',
  '- Exceptions for IP, injunctive relief, small claims',
  '',
  '15. General Provisions',
  '- Entire agreement with Privacy Policy',
  '- Severability, no waiver, assignment rules',
  '- Survival of key provisions',
  '- Not liable for force majeure',
  '- Updates notified via email/app',
  '- Contact: capturefit1@gmail.com',
  '',
  'By using CaptureFit, you agree to these Terms.',
  'Last updated: September 15, 2025'
].join('\n');
