name: Deploy Supabase Functions

on:
  push:
    branches: [ feature/backend, main ]

jobs:
  deploy-functions:
    name: Deploy Supabase Edge Functions
    runs-on: ubuntu-latest
    env:
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Deploy aicoach function
        run: |
          npx supabase@latest functions deploy aicoach --project-ref ${SUPABASE_PROJECT_REF} --no-verify-jwt
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Deploy delete-account function
        run: |
          npx supabase@latest functions deploy delete-account --project-ref ${SUPABASE_PROJECT_REF} --no-verify-jwt
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Set function secrets (OPENAI & service role) on project
        run: |
          npx supabase@latest secrets set OPENAI_API_KEY=${OPENAI_API_KEY} SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY} SUPABASE_URL=${SUPABASE_URL} --project-ref ${SUPABASE_PROJECT_REF}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Verify functions
        run: |
          echo "Deployed functions. You can test them via the Supabase UI or using the Supabase CLI."
